services:
  - type: web
    name: dark-kurd
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /
    envVars:
      - key: ADMIN_PASSWORD
        sync: false
      - key: APP_SECRET
        generateValue: true
